import { Metadata } from "next";
import "./styles/globals.css";
import "./styles/homeCSS.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Speed Otaku Central",
  description: "Generated by Next.js",
  applicationName: "Speed Otaku Central",
  category: "Animes e Mangás",
  authors: [
    { name: "Speed Uzumaki", url: "https://www.youtube.com/@SpeedUzumaki" },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
